services:
  postgres-db:
    image: postgres:15
    container_name: postgres_code_fix
    environment:
      POSTGRES_DB: codefix_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
    ports:
      - "5432:5432"

  api:
    build: .
    container_name: code_fix_api
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/codefix_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: adminpassword